postgresql:
  postgresqlUsername: "qc"
  postgresqlPassword: "qc"
  postgresqlDatabase: "qc"
  service:
    type: ClusterIP
    port: 5432
rabbitmq:
  auth:
    username: "qc"
    password: "qc"
  service:
    type: ClusterIP
    port: 5672
