apiVersion: v1
kind: ConfigMap
metadata:
  name: config-script
data:
  modify-config.sh: |
    #!/bin/sh
    ls -la
    pwd
    sed -i 's/original_broker_url/amqp:\/\/qc:qc@betterscan-rabbitmq:5672/' default.yml
    sed -i 's/original_result_backend/rpc:\/\/qc:qc@betterscan-rabbitmq:5672/' default.yml
    sed -i 's/original_db_url/postgresql:\/\/qc:qc@betterscan-postgres\/qc/' default.yml

