
apiVersion: apps/v1
kind: Pod
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13.2
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: qc
        - name: POSTGRES_USER
          value: qc
        - name: POSTGRES_PASSWORD
          value: qc
