
apiVersion: apps/v1
kind: Pod
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.8-management-alpine
        env:
          - name: RABBITMQ_DEFAULT_USER
            value: qc
          - name: RABBITMQ_DEFAULT_PASS
            value: qc
        ports:
        - containerPort: 5672
        - containerPort: 15672
