
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: scanmycode/scanmycode3-ce:server
        command: ["/bin/sh", "-c"]
        args: ["python /srv/scanmycode/manage.py setup && python /srv/scanmycode/manage.py runserver"]
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: server1
          mountPath: /srv/scanmycode/quantifiedcode/data/repositories/
        - name: server2
          mountPath: /srv/scanmycode/quantifiedcode/backend/data/tasks/
      volumes:
        - name: server1
          persistentVolumeClaim:
            claimName: pvc-for-server1
        - name: server2
          persistentVolumeClaim:
            claimName: pvc-for-server2
