
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: sunsolution/betterscan-server:latest
        workingDir: /srv/betterscan/
        command: ["/bin/sh", "-c"]
        args: ["cp /scripts/modify-config.sh /tmp && chmod +x /tmp/modify-config.sh && /tmp/modify-config.sh && python /srv/betterscan/manage.py setup && python /srv/betterscan/manage.py runserver"]
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
        - name: server1
          mountPath: /srv/betterscan/quantifiedcode/data/repositories/
        - name: server2
          mountPath: /srv/betterscan/quantifiedcode/backend/data/tasks/
      volumes:
        - name: server1
          persistentVolumeClaim:
            claimName: pvc-for-server1
        - name: server2
          persistentVolumeClaim:
            claimName: pvc-for-server2
        - name: script-volume
          configMap:
            name: config-script
