apiVersion: v1
kind: Service
metadata:
  name: platform
spec:
  selector:
    app: server  # Match labels of your pod(s)
  ports:
    - protocol: TCP
      port: 5000     # Port to expose on the service
      targetPort: 5000  # Port on the pods to forward traffic to
  type: LoadBalancer  # Use the appropriate service type (ClusterIP, NodePort, LoadBalancer, etc.)

