apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
  - name: debug-container
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: config-volume
      mountPath: /mnt
  volumes:
  - name: config-volume
    persistentVolumeClaim:
      claimName: pvc-config
