
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: scanmycode/scanmycode3-ce:worker
        workingDir: /srv/scanmycode/
        command: ["/bin/sh", "-c"]
        args: ["python /srv/scanmycode/manage.py runworker"]
        volumeMounts:
        - name: server1
          mountPath: /srv/scanmycode/quantifiedcode/data/repositories/
        - name: server2
          mountPath: /srv/scanmycode/quantifiedcode/backend/data/tasks/
      volumes:
        - name: server1
          persistentVolumeClaim:
            claimName: pvc-for-server1
        - name: server2
          persistentVolumeClaim:
            claimName: pvc-for-server2
