
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: sunsolution/betterscan-worker:latest
        workingDir: /srv/betterscan/
        command: ["/bin/sh", "-c"]
        args: ["cp /scripts/modify-config.sh /tmp && chmod +x /tmp/modify-config.sh && /tmp/modify-config.sh && python /srv/betterscan/manage.py runworker"]
        volumeMounts:
        - name: script-volume
          mountPath: /scripts
        - name: server1
          mountPath: /srv/betterscan/quantifiedcode/data/repositories/
        - name: server2
          mountPath: /srv/betterscan/quantifiedcode/backend/data/tasks/
      volumes:
        - name: server1
          persistentVolumeClaim:
            claimName: pvc-for-server1
        - name: server2
          persistentVolumeClaim:
            claimName: pvc-for-server2
        - name: script-volume
          configMap:
            name: config-script
